### ISSUE TITLE
`.yaydoc.yml` in this repo still uses the old design

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#317]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

```yaml
build:
  doctheme: sphinx_fossasia_theme
  docpath: docs/
```

### Expected behaviour

```yaml
build:
  theme: sphinx_fossasia_theme
  source: docs
```
