### ISSUE TITLE
Expose theme options to the .yaydoc.yml file

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#332]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently to specify theme options, user will have to provide a conf.py with the options.

### Expected behaviour

Theme options should be exposed to the yaml file so that users can provide them.
eg.
```yaml
build:
  theme:
    name: my_theme
    options:
      - "option1=value1"
      - "option2=value2"
```

### Steps to reproduce
1.
2.
3.
